// <auto-generated />
using System;
using Merchello.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Merchello.Core.Sqlite.Migrations
{
    [DbContext(typeof(MerchelloDbContext))]
    [Migration("20251216154732_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustedSubTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateDeleted")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DiscountInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricingExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("PricingExchangeRateSource")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PricingExchangeRateTimestampUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PurchaseOrder")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StoreCurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SubTotalInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TaxInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("TotalInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyCode");

                    b.HasIndex("IsDeleted");

                    b.ToTable("merchelloInvoices", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AmountInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependantLineItemSku")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("merchelloLineItems", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryDateSurcharge")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryDateSurchargeInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeliveryDateGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessingStartedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("ShippingCostInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("merchelloOrders", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("AmountInStoreCurrency")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FraudResponse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ParentPaymentId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentProviderAlias")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PaymentSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaymentType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("RefundReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SettlementAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementCurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("SettlementExchangeRate")
                        .HasPrecision(18, 8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettlementExchangeRateSource")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ParentPaymentId");

                    b.HasIndex("InvoiceId", "PaymentSuccess");

                    b.ToTable("merchelloPayments", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.TaxGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloTaxGroups", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Checkout.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustedSubTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineItems")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shipping")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloBaskets", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.ExchangeRates.Models.ExchangeRateProviderSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConfigurationJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastFetchedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastRatesJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderAlias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("ProviderAlias")
                        .IsUnique();

                    b.ToTable("merchelloExchangeRateProviders", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Payments.Models.PaymentProviderSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Configuration")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTestMode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderAlias")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProviderAlias")
                        .IsUnique();

                    b.ToTable("merchelloPaymentProviders", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvailableForPurchase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanPurchase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfGoods")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludeRootProductImages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gtin")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("HsCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OnSale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PackageConfigurations")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoveFromFeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShippingRestrictionMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ShoppingFeedColour")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedSize")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantOptionsKey")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Price");

                    b.HasIndex("ProductRootId");

                    b.HasIndex("Url");

                    b.ToTable("merchelloProducts", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloProductCategories", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HexColour")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductFilterGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductFilterGroupId");

                    b.ToTable("merchelloProductFilters", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilterGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("merchelloProductFilterGroups", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultPackageConfigurations")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementPropertyData")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleShoppingFeedCategory")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDigitalProduct")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenGraphImage")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductOptions")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootImages")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ViewAlias")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("RootUrl");

                    b.HasIndex("TaxGroupId");

                    b.ToTable("merchelloProductRoots", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRootWarehouse", b =>
                {
                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductRootId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloProductRootWarehouse", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloProductTypes", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehouse", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReorderPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReorderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("ProductId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloProductWarehouse", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehousePriceOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostOfGoods")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloProductWarehousePriceOverride", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourierId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeliveryDateGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineItems")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingUrl")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloShipments", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateOrProvinceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShippingOptionId");

                    b.ToTable("merchelloShippingCosts", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDaysOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowsDeliveryDateSelection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationMethod")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryDatePricingMethod")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FixedCost")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeliveryDateGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsNextDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxDeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("NextDayCutOffTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("flat-rate");

                    b.Property<string>("ProviderSettings")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloShippingOptions", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOptionCountry", b =>
                {
                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ShippingOptionId", "CountryCode");

                    b.ToTable("merchelloShippingOptionCountries", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingProviderConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProviderKey")
                        .IsUnique();

                    b.ToTable("merchelloShippingProviderConfigurations", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingWeightTier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxWeightKg")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("MinWeightKg")
                        .HasColumnType("decimal(18,4)");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateOrProvinceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Surcharge")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShippingOptionId", "CountryCode", "StateOrProvinceCode");

                    b.ToTable("merchelloShippingWeightTiers", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Suppliers.Models.Supplier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactName")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloSuppliers", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationMethod")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("SupplierId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.ToTable("merchelloWarehouses", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.WarehouseServiceRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateOrProvinceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloWarehouseServiceRegions", (string)null);
                });

            modelBuilder.Entity("ProductShippingOption", b =>
                {
                    b.Property<Guid>("AllowedShippingOptionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedShippingOptionsId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("merchelloProductAllowedShippingOptions", (string)null);
                });

            modelBuilder.Entity("ProductShippingOption1", b =>
                {
                    b.Property<Guid>("ExcludedShippingOptionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Product1Id")
                        .HasColumnType("TEXT");

                    b.HasKey("ExcludedShippingOptionsId", "Product1Id");

                    b.HasIndex("Product1Id");

                    b.ToTable("merchelloProductExcludedShippingOptions", (string)null);
                });

            modelBuilder.Entity("merchelloProductFiltersProducts", b =>
                {
                    b.Property<Guid>("FilterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilterId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("merchelloProductFiltersProducts");
                });

            modelBuilder.Entity("merchelloProductRootCategories", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId", "ProductRootId");

                    b.HasIndex("ProductRootId");

                    b.ToTable("merchelloProductRootCategories");
                });

            modelBuilder.Entity("merchelloProductRootShippingOptions", b =>
                {
                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductRootId", "ShippingOptionId");

                    b.HasIndex("ShippingOptionId");

                    b.ToTable("merchelloProductRootShippingOptions");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Invoice", b =>
                {
                    b.OwnsOne("Merchello.Core.Locality.Models.Address", "BillingAddress", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressOne")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingAddressOne");

                            b1.Property<string>("AddressTwo")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingAddressTwo");

                            b1.Property<string>("Company")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingCompany");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingCountry");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingCountryCode");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingEmail");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingPhone");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingPostalCode");

                            b1.Property<string>("TownCity")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("BillingTownCity");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("merchelloInvoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");

                            b1.OwnsOne("Merchello.Core.Locality.Models.CountyState", "CountyState", b2 =>
                                {
                                    b2.Property<Guid>("AddressInvoiceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("BillingCountyStateName");

                                    b2.Property<string>("RegionCode")
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("BillingCountyStateCode");

                                    b2.HasKey("AddressInvoiceId");

                                    b2.ToTable("merchelloInvoices");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressInvoiceId");
                                });

                            b1.Navigation("CountyState")
                                .IsRequired();
                        });

                    b.OwnsOne("Merchello.Core.Locality.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressOne")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingAddressOne");

                            b1.Property<string>("AddressTwo")
                                .HasMaxLength(500)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingAddressTwo");

                            b1.Property<string>("Company")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingCompany");

                            b1.Property<string>("Country")
                                .HasMaxLength(100)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingCountry");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(10)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingCountryCode");

                            b1.Property<string>("Email")
                                .HasMaxLength(254)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingEmail");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingName");

                            b1.Property<string>("Phone")
                                .HasMaxLength(50)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingPhone");

                            b1.Property<string>("PostalCode")
                                .HasMaxLength(20)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingPostalCode");

                            b1.Property<string>("TownCity")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("ShippingTownCity");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("merchelloInvoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");

                            b1.OwnsOne("Merchello.Core.Locality.Models.CountyState", "CountyState", b2 =>
                                {
                                    b2.Property<Guid>("AddressInvoiceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasMaxLength(200)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ShippingCountyStateName");

                                    b2.Property<string>("RegionCode")
                                        .HasMaxLength(10)
                                        .HasColumnType("TEXT")
                                        .HasColumnName("ShippingCountyStateCode");

                                    b2.HasKey("AddressInvoiceId");

                                    b2.ToTable("merchelloInvoices");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressInvoiceId");
                                });

                            b1.Navigation("CountyState")
                                .IsRequired();
                        });

                    b.Navigation("BillingAddress")
                        .IsRequired();

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.LineItem", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Merchello.Core.Accounting.Models.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Invoice");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Order", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Invoice", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Payment", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Accounting.Models.Payment", "ParentPayment")
                        .WithMany("Refunds")
                        .HasForeignKey("ParentPaymentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Invoice");

                    b.Navigation("ParentPayment");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.Product", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductRoot", "ProductRoot")
                        .WithMany("Products")
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRoot");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilter", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductFilterGroup", "ParentGroup")
                        .WithMany("Filters")
                        .HasForeignKey("ProductFilterGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRoot", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Accounting.Models.TaxGroup", "TaxGroup")
                        .WithMany("Products")
                        .HasForeignKey("TaxGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("TaxGroup");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRootWarehouse", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductRoot", "ProductRoot")
                        .WithMany("ProductRootWarehouses")
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ProductRootWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRoot");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehouse", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.Product", "Product")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehousePriceOverride", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.Product", "Product")
                        .WithMany("ProductWarehousePriceOverrides")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ProductWarehousePriceOverrides")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.Shipment", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingCost", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", "ShippingOption")
                        .WithMany("ShippingCosts")
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingOption");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOption", b =>
                {
                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ShippingOptions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOptionCountry", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", "ShippingOption")
                        .WithMany("ShippingOptionCountries")
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Merchello.Core.Locality.Models.Country", "Country", b1 =>
                        {
                            b1.Property<Guid>("ShippingOptionCountryShippingOptionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ShippingOptionCountryCountryCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.HasKey("ShippingOptionCountryShippingOptionId", "ShippingOptionCountryCountryCode");

                            b1.ToTable("merchelloShippingOptionCountries");

                            b1.WithOwner()
                                .HasForeignKey("ShippingOptionCountryShippingOptionId", "ShippingOptionCountryCountryCode");

                            b1.OwnsMany("Merchello.Core.Locality.Models.CountyState", "CountyStates", b2 =>
                                {
                                    b2.Property<Guid>("CountryShippingOptionCountryShippingOptionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CountryShippingOptionCountryCountryCode")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RegionCode")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("CountryShippingOptionCountryShippingOptionId", "CountryShippingOptionCountryCountryCode", "Id");

                                    b2.ToTable("merchelloShippingOptionCountries_CountyStates");

                                    b2.WithOwner()
                                        .HasForeignKey("CountryShippingOptionCountryShippingOptionId", "CountryShippingOptionCountryCountryCode");
                                });

                            b1.Navigation("CountyStates");
                        });

                    b.Navigation("Country")
                        .IsRequired();

                    b.Navigation("ShippingOption");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingWeightTier", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", "ShippingOption")
                        .WithMany("WeightTiers")
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingOption");
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.Warehouse", b =>
                {
                    b.HasOne("Merchello.Core.Suppliers.Models.Supplier", "Supplier")
                        .WithMany("Warehouses")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.WarehouseServiceRegion", b =>
                {
                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ServiceRegions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProductShippingOption", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", null)
                        .WithMany()
                        .HasForeignKey("AllowedShippingOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductShippingOption1", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", null)
                        .WithMany()
                        .HasForeignKey("ExcludedShippingOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("Product1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("merchelloProductFiltersProducts", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductFilter", null)
                        .WithMany()
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("merchelloProductRootCategories", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.ProductRoot", null)
                        .WithMany()
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("merchelloProductRootShippingOptions", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", null)
                        .WithMany()
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Invoice", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Order", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Payment", b =>
                {
                    b.Navigation("Refunds");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.TaxGroup", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.Product", b =>
                {
                    b.Navigation("ProductWarehousePriceOverrides");

                    b.Navigation("ProductWarehouses");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilterGroup", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRoot", b =>
                {
                    b.Navigation("ProductRootWarehouses");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOption", b =>
                {
                    b.Navigation("ShippingCosts");

                    b.Navigation("ShippingOptionCountries");

                    b.Navigation("WeightTiers");
                });

            modelBuilder.Entity("Merchello.Core.Suppliers.Models.Supplier", b =>
                {
                    b.Navigation("Warehouses");
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.Warehouse", b =>
                {
                    b.Navigation("ProductRootWarehouses");

                    b.Navigation("ProductWarehousePriceOverrides");

                    b.Navigation("ProductWarehouses");

                    b.Navigation("ServiceRegions");

                    b.Navigation("ShippingOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
