// <auto-generated />
using System;
using Merchello.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Merchello.Core.Sqlite.Migrations
{
    [DbContext(typeof(MerchelloDbContext))]
    partial class MerchelloDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustedSubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adjustments")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxRounding")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloInvoices", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.LineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("DependantLineItemSku")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LineItemType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("OriginalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("merchelloLineItems", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CancelledDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("DeliveryDateSurcharge")
                        .HasColumnType("TEXT");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeliveryDateGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ProcessingStartedDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ShippingCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("merchelloOrders", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Payment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FraudResponse")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<bool>("PaymentSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("merchelloPayments", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.TaxGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TaxPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloTaxGroups", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Checkout.Models.Basket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("AdjustedSubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Adjustments")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Currency")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencySymbol")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Discount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("LineItems")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Shipping")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Tax")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("TaxRounding")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Total")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloBaskets", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AvailableForPurchase")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CanPurchase")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("CostOfGoods")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Default")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<bool>("ExcludeFromCustomLabels")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ExcludeRootProductImages")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Gtin")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Images")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoIndex")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OnSale")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OpenGraphImage")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageTitle")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PreviousPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RemoveFromFeed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShippingRestrictionMode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<string>("ShoppingFeedColour")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedDescription")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedMaterial")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedSize")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShoppingFeedTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sku")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("SupplierSku")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("VariantOptionsKey")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Price");

                    b.HasIndex("ProductRootId");

                    b.ToTable("merchelloProducts", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloProductCategories", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("HexColour")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductFilterGroupId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductFilterGroupId");

                    b.ToTable("merchelloProductFilters", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilterGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("merchelloProductFilterGroups", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRoot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleShoppingFeedCategory")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HsCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductOptions")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductTypeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootImages")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("RootName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RootUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SellingPoints")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TaxGroupId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Videos")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Weight")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.HasIndex("TaxGroupId");

                    b.ToTable("merchelloProductRoots", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRootWarehouse", b =>
                {
                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PriorityOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductRootId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloProductRootWarehouse", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloProductTypes", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehouse", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReorderPoint")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ReorderQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<int>("Stock")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TrackStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.HasKey("ProductId", "WarehouseId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloProductWarehouse", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehousePriceOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("CostOfGoods")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloProductWarehousePriceOverride", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Carrier")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CourierId")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("IsDeliveryDateGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineItems")
                        .IsRequired()
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RequestedDeliveryDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackingUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("SupplierId");

                    b.ToTable("merchelloShipments", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingCost", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StateOrProvinceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ShippingOptionId");

                    b.ToTable("merchelloShippingCosts", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AllowedDaysOfWeek")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowsDeliveryDateSelection")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CalculationMethod")
                        .HasMaxLength(1500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("DaysFrom")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysTo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryDatePricingMethod")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("FixedCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeliveryDateGuaranteed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNextDay")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MaxDeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MinDeliveryDays")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(350)
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("NextDayCutOffTime")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloShippingOptions", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOptionCountry", b =>
                {
                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ShippingOptionId", "CountryCode");

                    b.ToTable("merchelloShippingOptionCountries", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingProviderConfiguration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("SettingsJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloShippingProviderConfigurations", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.Warehouse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AutomationMethod")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExtendedData")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("merchelloWarehouses", (string)null);
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.WarehouseServiceRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StateOrProvinceCode")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("WarehouseId");

                    b.ToTable("merchelloWarehouseServiceRegions", (string)null);
                });

            modelBuilder.Entity("ProductShippingOption", b =>
                {
                    b.Property<Guid>("AllowedShippingOptionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("AllowedShippingOptionsId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("merchelloProductAllowedShippingOptions", (string)null);
                });

            modelBuilder.Entity("ProductShippingOption1", b =>
                {
                    b.Property<Guid>("ExcludedShippingOptionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("Product1Id")
                        .HasColumnType("TEXT");

                    b.HasKey("ExcludedShippingOptionsId", "Product1Id");

                    b.HasIndex("Product1Id");

                    b.ToTable("merchelloProductExcludedShippingOptions", (string)null);
                });

            modelBuilder.Entity("merchelloProductFiltersProducts", b =>
                {
                    b.Property<Guid>("FilterId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("FilterId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("merchelloProductFiltersProducts");
                });

            modelBuilder.Entity("merchelloProductRootCategories", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId", "ProductRootId");

                    b.HasIndex("ProductRootId");

                    b.ToTable("merchelloProductRootCategories");
                });

            modelBuilder.Entity("merchelloProductRootShippingOptions", b =>
                {
                    b.Property<Guid>("ProductRootId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ShippingOptionId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductRootId", "ShippingOptionId");

                    b.HasIndex("ShippingOptionId");

                    b.ToTable("merchelloProductRootShippingOptions");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.LineItem", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId");

                    b.HasOne("Merchello.Core.Accounting.Models.Order", "Order")
                        .WithMany("LineItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Invoice");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Order", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Invoice", "Invoice")
                        .WithMany("Orders")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Merchello.Core.Locality.Models.Address", "ShippingAddress", b1 =>
                        {
                            b1.Property<Guid>("OrderId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressOne")
                                .HasColumnType("TEXT");

                            b1.Property<string>("AddressTwo")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Company")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Email")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Phone")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("TownCity")
                                .HasColumnType("TEXT");

                            b1.HasKey("OrderId");

                            b1.ToTable("merchelloOrders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");

                            b1.OwnsOne("Merchello.Core.Locality.Models.CountyState", "CountyState", b2 =>
                                {
                                    b2.Property<Guid>("AddressOrderId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RegionCode")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("AddressOrderId");

                                    b2.ToTable("merchelloOrders");

                                    b2.WithOwner()
                                        .HasForeignKey("AddressOrderId");
                                });

                            b1.Navigation("CountyState")
                                .IsRequired();
                        });

                    b.Navigation("Invoice");

                    b.Navigation("ShippingAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Payment", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Invoice", "Invoice")
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.Product", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductRoot", "ProductRoot")
                        .WithMany("Products")
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRoot");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilter", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductFilterGroup", "ParentGroup")
                        .WithMany("Filters")
                        .HasForeignKey("ProductFilterGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParentGroup");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRoot", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductType", "ProductType")
                        .WithMany("Products")
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Accounting.Models.TaxGroup", "TaxGroup")
                        .WithMany("Products")
                        .HasForeignKey("TaxGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductType");

                    b.Navigation("TaxGroup");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRootWarehouse", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductRoot", "ProductRoot")
                        .WithMany("ProductRootWarehouses")
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ProductRootWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductRoot");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehouse", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.Product", "Product")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ProductWarehouses")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductWarehousePriceOverride", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.Product", "Product")
                        .WithMany("ProductWarehousePriceOverrides")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ProductWarehousePriceOverrides")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.Shipment", b =>
                {
                    b.HasOne("Merchello.Core.Accounting.Models.Order", "Order")
                        .WithMany("Shipments")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingCost", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", "ShippingOption")
                        .WithMany("ShippingCosts")
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingOption");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOption", b =>
                {
                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ShippingOptions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOptionCountry", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", "ShippingOption")
                        .WithMany("ShippingOptionCountries")
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Merchello.Core.Locality.Models.Country", "Country", b1 =>
                        {
                            b1.Property<Guid>("ShippingOptionCountryShippingOptionId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ShippingOptionCountryCountryCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.HasKey("ShippingOptionCountryShippingOptionId", "ShippingOptionCountryCountryCode");

                            b1.ToTable("merchelloShippingOptionCountries");

                            b1.WithOwner()
                                .HasForeignKey("ShippingOptionCountryShippingOptionId", "ShippingOptionCountryCountryCode");

                            b1.OwnsMany("Merchello.Core.Locality.Models.CountyState", "CountyStates", b2 =>
                                {
                                    b2.Property<Guid>("CountryShippingOptionCountryShippingOptionId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("CountryShippingOptionCountryCountryCode")
                                        .HasColumnType("TEXT");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Name")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("RegionCode")
                                        .HasColumnType("TEXT");

                                    b2.HasKey("CountryShippingOptionCountryShippingOptionId", "CountryShippingOptionCountryCountryCode", "Id");

                                    b2.ToTable("merchelloShippingOptionCountries_CountyStates");

                                    b2.WithOwner()
                                        .HasForeignKey("CountryShippingOptionCountryShippingOptionId", "CountryShippingOptionCountryCountryCode");
                                });

                            b1.Navigation("CountyStates");
                        });

                    b.Navigation("Country")
                        .IsRequired();

                    b.Navigation("ShippingOption");
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.WarehouseServiceRegion", b =>
                {
                    b.HasOne("Merchello.Core.Warehouses.Models.Warehouse", "Warehouse")
                        .WithMany("ServiceRegions")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("ProductShippingOption", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", null)
                        .WithMany()
                        .HasForeignKey("AllowedShippingOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProductShippingOption1", b =>
                {
                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", null)
                        .WithMany()
                        .HasForeignKey("ExcludedShippingOptionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("Product1Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("merchelloProductFiltersProducts", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductFilter", null)
                        .WithMany()
                        .HasForeignKey("FilterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("merchelloProductRootCategories", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.ProductCategory", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Products.Models.ProductRoot", null)
                        .WithMany()
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("merchelloProductRootShippingOptions", b =>
                {
                    b.HasOne("Merchello.Core.Products.Models.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductRootId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Merchello.Core.Shipping.Models.ShippingOption", null)
                        .WithMany()
                        .HasForeignKey("ShippingOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Invoice", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.Order", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("Merchello.Core.Accounting.Models.TaxGroup", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.Product", b =>
                {
                    b.Navigation("ProductWarehousePriceOverrides");

                    b.Navigation("ProductWarehouses");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductFilterGroup", b =>
                {
                    b.Navigation("Filters");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductRoot", b =>
                {
                    b.Navigation("ProductRootWarehouses");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("Merchello.Core.Products.Models.ProductType", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Merchello.Core.Shipping.Models.ShippingOption", b =>
                {
                    b.Navigation("ShippingCosts");

                    b.Navigation("ShippingOptionCountries");
                });

            modelBuilder.Entity("Merchello.Core.Warehouses.Models.Warehouse", b =>
                {
                    b.Navigation("ProductRootWarehouses");

                    b.Navigation("ProductWarehousePriceOverrides");

                    b.Navigation("ProductWarehouses");

                    b.Navigation("ServiceRegions");

                    b.Navigation("ShippingOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
